/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 20:22:33 GMT 2024
 */

package br.ufrn.imd.execucao01.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufrn.imd.Estoque;
import br.ufrn.imd.Produto;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Estoque_ESTest extends Estoque_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto("UMp@MeueLc2:)m/m5i2", "UMp@MeueLc2:)m/m5i2", 0.0);
      estoque0.inserirProduto(produto0, 0);
      estoque0.removerProduto("UMp@MeueLc2:)m/m5i2", 1051);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto("4[r_84?|<", "4[r_84?|<", 0.0);
      estoque0.inserirProduto(produto0, 295);
      estoque0.removerProduto("4[r_84?|<", 0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto("y&w~ \"", "y&w~ \"", 49.68902773182108);
      estoque0.inserirProduto(produto0, 1);
      estoque0.inserirProduto(produto0, 1518);
      assertEquals("y&w~ \"", produto0.getNome());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto("y&w~ \"", "y&w~ \"", 49.68902773182108);
      estoque0.inserirProduto(produto0, 1);
      int int0 = estoque0.consultarQuantidade("y&w~ \"");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      // Undeclared exception!
      try { 
        estoque0.inserirProduto((Produto) null, (-2476));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.ufrn.imd.Estoque", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      boolean boolean0 = estoque0.produtoExiste((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto((String) null, "", 0.0);
      estoque0.inserirProduto(produto0, 1);
      boolean boolean0 = estoque0.produtoExiste("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto("}:0e\"HrRqRpa+t", "", 12.418);
      estoque0.inserirProduto(produto0, (-2004318069));
      int int0 = estoque0.consultarQuantidade("");
      assertEquals((-2004318069), int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      int int0 = estoque0.consultarQuantidade("#'gYR`D?E");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      try { 
        estoque0.removerProduto("#'gYR`D?E", 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // O produto de c\u00F3digo #'gYR`D?E n\u00E3o existe no estoque.
         //
         verifyException("br.ufrn.imd.Estoque", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Estoque estoque0 = new Estoque();
      Produto produto0 = new Produto("br.bufrn_{idEstozN", "br.bufrn_{idEstozN", (-29));
      estoque0.inserirProduto(produto0, (-29));
      estoque0.removerProduto("br.bufrn_{idEstozN", (-29));
  }
}
