/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 20:22:37 GMT 2024
 */

package br.ufrn.imd.execucao01.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import br.ufrn.imd.Produto;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Produto_ESTest extends Produto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Produto produto0 = new Produto("", "", 3575.587295515531);
      produto0.setPreco(0.0);
      double double0 = produto0.getPreco();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Produto produto0 = new Produto("%8Uu", "]Z", (-123.434256049));
      double double0 = produto0.getPreco();
      assertEquals("%8Uu", produto0.getNome());
      assertEquals((-123.434256049), double0, 0.01);
      assertEquals("]Z", produto0.getCodigo());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 0.0);
      produto0.getNome();
      assertEquals(0.0, produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Produto produto0 = new Produto("", "", 3575.587295515531);
      produto0.setNome("&7(T(nt?-H}mYN=?");
      produto0.getNome();
      assertEquals(3575.587295515531, produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Produto produto0 = new Produto((String) null, (String) null, 0.0);
      produto0.getCodigo();
      assertEquals(0.0, produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Produto produto0 = new Produto("", "", 3575.587295515531);
      produto0.setCodigo("br.ufrn.imd.Produto");
      produto0.getCodigo();
      assertEquals(3575.587295515531, produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Produto produto0 = new Produto("", "", 3575.587295515531);
      double double0 = produto0.getPreco();
      assertEquals(3575.587295515531, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Produto produto0 = new Produto("", "", 3575.587295515531);
      produto0.getNome();
      assertEquals(3575.587295515531, produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Produto produto0 = new Produto("", "", 3575.587295515531);
      produto0.getCodigo();
      assertEquals(3575.587295515531, produto0.getPreco(), 0.01);
  }
}
