/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 20:28:09 GMT 2024
 */

package br.ufrn.imd.execucao02.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import br.ufrn.imd.Produto;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Produto_ESTest extends Produto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Produto produto0 = new Produto("|ZmT;C", "|ZmT;C", (-1.0));
      produto0.setPreco(0.0);
      double double0 = produto0.getPreco();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Produto produto0 = new Produto("|ZmT;C", "|ZmT;C", (-1.0));
      double double0 = produto0.getPreco();
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Produto produto0 = new Produto("|ZmT;C", "|ZmT;C", (-1.0));
      produto0.setNome((String) null);
      produto0.getNome();
      assertEquals((-1.0), produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Produto produto0 = new Produto("|ZmT;C", "|ZmT;C", (-1.0));
      produto0.getNome();
      assertEquals((-1.0), produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Produto produto0 = new Produto("|ZmT;C", "|ZmT;C", (-1.0));
      produto0.setCodigo((String) null);
      produto0.getCodigo();
      assertEquals((-1.0), produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Produto produto0 = new Produto("", "EAjn", (-1.0));
      String string0 = produto0.getCodigo();
      assertEquals((-1.0), produto0.getPreco(), 0.01);
      assertEquals("", produto0.getNome());
      assertEquals("EAjn", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Produto produto0 = new Produto("", "", 267.0551038641595);
      double double0 = produto0.getPreco();
      assertEquals(267.0551038641595, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Produto produto0 = new Produto("", "", 1.0);
      produto0.getNome();
      assertEquals(1.0, produto0.getPreco(), 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Produto produto0 = new Produto("", "", 1.0);
      produto0.getCodigo();
      assertEquals(1.0, produto0.getPreco(), 0.01);
  }
}
